#ifndef WANNIERMC_CONFIG_H
#define WANNIERMC_CONFIG_H

//Configuration definitions processed by Cmake
//	Do not edit config.h, it is generated by Cmake
//	Edit config.in.h instead

#define PACKAGE_NAME "${CPACK_PACKAGE_NAME}"
#define VERSION_STRING "${VERSION_STRING}"
#define GIT_HASH "${GIT_HASH}"

#endif // WANNIERMC_CONFIG_H
