/*-------------------------------------------------------------------
Copyright 2018 Ravishankar Sundararaman

This file is part of JDFTx.

JDFTx is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JDFTx is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with JDFTx.  If not, see <http://www.gnu.org/licenses/>.
-------------------------------------------------------------------*/

#ifndef FEYNWANN_FEYNWANN_H
#define FEYNWANN_FEYNWANN_H

#include "DistributedMatrix.h"

//! Parameters for initializing Wannier
struct FeynWannParams
{	int iSpin; //!< current spin channel: 0(up) or 1(dn) for z-spin calculations; must be 0 for all other spin types
	string totalEprefix; //!< filename prefix for DFT outputs (default: Wannier/totalE)
	string phononPrefix; //!< filename prefix for phonon outputs (default: Wannier/phonon)
	string wannierPrefix; //!< filename prefix for wannier outputs (default: Wannier/wannier)
	bool needSymmetries; //!< whether to read symmetries from .sym file from JDFTx (default: false)
	bool needCellWeights; //!< whether to read mlwfCellWeights file (default: false)
	bool needPhonons; //!< whether to initialize phonon-related quantities (default: false)
	bool needVelocity; //!< whether to initialize velocity (momentum) matrix elements
	bool needSpin; //!< whether to initialize spin matrix elements (will be reset to false if not relativstic)
	bool needLinewidth_ee; //!< whether to provide e-e line-width (default: false)
	bool needLinewidth_ePh; //!< whether to provide e-ph line-width (default: false)
	bool needLinewidthP_ePh; //!< whether to provide momentum-relaxation e-ph line-width (default: false)
	bool ePhHeadOnly; //!< if true, only evaluate ePh callback function at head of each offset for debugging (default: false)
	static const std::vector<double> fGrid_ePh; //!< fillings grid used for e-ph linewidths
	FeynWannParams();
};

//! Wannier interpolator for electrons and phonons
class FeynWann
{
public:
	static InitParams initialize(int argc, char** argv, const char* description); //!< wrap initSystemCmdLine from JDFTx
	static void finalize(); //!< wrap finalizeSystem from JDFTx
	static vector3<> randomVector(MPIUtil* mpiUtil=0); //!< uniformly random vector in [0,1)^3, constant across mpi instance, if any

	const FeynWannParams& fwp;
	FeynWann(FeynWannParams& fwp);
	void free(); //!< free matrices
	inline bool isRelativistic() const { return nSpinor==2; }
	
	//! Electronic properties at a given wave vector
	struct StateE
	{	int ik; //!< index in mesh of dimensions kfold
		vector3<> k; //!< wave-vector in recip lattice coords
		diagMatrix E; //!< energy relative to Fermi level (FeynWann::mu)
		matrix U; //!< rotation from Wannier to eiegen-basis
		matrix v[3]; //!< velocity matrix elements in Cartesian coordinates, available if needVelocity = true
		std::vector<vector3<>> vVec; //!< band velocities (diagonal part of v) in Cartesian coordinates, available if needVelocity = true
		matrix S[3]; //!< Spin matrix elements in Cartesian coordinates, available if needSpin = true
		std::vector<vector3<>> Svec; //!< band spins (diagonal part of S) in Cartesian coordinates, available if needSpin = true
		diagMatrix ImSigma_ee; //!< e-e linewidth, available if needLinewidth_ee = true
		double ImSigma_ePh(int n, double f) const; //!< get e-ph linewidth for band n given its occupation f, available if needLinewidth_ePh = true
		double ImSigmaP_ePh(int n, double f) const; //!< get e-ph linewidth for band n given its occupation f, available if needLinewidthP_ePh = true
	private:
		std::vector<diagMatrix> logImSigma_ePhArr; //!< e-ph linewidth for each f in fGrid_ePh
		std::vector<diagMatrix> logImSigmaP_ePhArr; //!< e-ph momentum-relaxation linewidth for each f in fGrid_ePh
		friend class FeynWann;
	};
	
	//! Phonon properties at a given wave vector
	struct StatePh
	{	int iq; //!< index in mesh of dimensions phononSup
		int iqFine; //!< index in mesh of dimensions kfold, only when generated by ePhLoop
		vector3<> q; //!< wave-vector in recip lattice coords
		diagMatrix omega; //!< frequency
		matrix U; //!< rotation from atom-displacement to eigen-basis
	};
	
	//! Electron-phonon matrix elements
	struct MatrixEph
	{	const StateE* e1; //!< corresponding first electronic state
		const StateE* e2; //!< corresponding second electronic state
		const StatePh* ph; //!< corresponding phonon state
		std::vector<matrix> M; //!< nModes matrices of nBands x nBands matrix elements
	};
	
	typedef void (*eProcessFunc)(const StateE& state, void* params); //!< Callback function pointer for eLoop()
	typedef void (*phProcessFunc)(const StatePh& state, void* params); //!< Callback function pointer for phLoop()
	typedef void (*ePhProcessFunc)(const MatrixEph& mat, void* params); //!< Callback function pointer for ePhLoop()
	
	//! Calculate electronic properties for each k-point in a mesh offset by k0
	//! Calls provided callback function eProcess on each of them, along with provided params
	void eLoop(const vector3<>& k0, eProcessFunc eProcess, void* params);
	size_t eCountPerOffset() const { return Hw->nkTot; } //!< number of k's sampled per offset
	
	//! Calculate phonon properties for each q-point in a mesh offset by q0
	//! Calls provided callback function phProcess on each of them, along with provided params
	void phLoop(const vector3<>& q0, phProcessFunc phProcess, void* params);
	size_t phCountPerOffset() const { return OsqW->nkTot; } //!< number of q's sampled per offset
	
	//! Calculate electronic properties for each pair of k-points between two meshes offset by k01 and k02,
	//! as well as phonon properties and electron-phonon matrix elements connecting these k-points.
	//! Calls provided callback function ePhProcess on each of them, along with provided params
	void ePhLoop(const vector3<>& k01, const vector3<>& k02, ePhProcessFunc ePhProcess, void* params);
	size_t ePhCountPerOffset() const { return Hw->nkTot * Hw->nkTot; } //!< number of k-pairs sampled per offset
	
	void symmetrize(matrix3<>& m) const; //!< symmetrize a tensor in Cartesian coordinates (available if needSymmetries = true)
	
	//DFT / Wannier / Phonon parameters:
	matrix3<> R; //!< lattice vectors
	std::vector<vector3<>> atpos; //!< atomic positions
	std::vector<string> atNames; //!< atom species names
	int nAtoms; //number of atoms
	double Omega; //!< unit cell volume
	vector3<int> kfold; //!< k-point folding in original calculation
	vector3<int> phononSup; //!< phonon supercell in original calculation
	vector3<int> kfoldSup; //!< k-point folding of phonon supercell i.e. kfold / phononSup
	vector3<bool> isTruncated; //!< whether each direction is truncated
	std::vector<SpaceGroupOp> sym; //!< symmetries of DFT calculation
	int nBands; //!< number of Wannier bands for the electrons
	int nSpins, nSpinor, spinWeight; //!< number of spin channels, spinor components and weight per spin channel
	bool realPartOnly; //!< whether wannier Hamiltonians / matrix elements in files are stored with real parts alone
	string spinSuffix; //filename suffix for current spin channel (if any)
	double mu; //!< chemical potential if DFT calculation had smearing, else VBM
	double nElectrons; //!< number of electrons per unit cell in DFT calculation
	double eMinMain, eMaxMain; //!< energy range for main window (within which eigenvalues should be exact compared to DFT)
	int nModes; //!< number of phonon modes (polarizations)
	
	//Electrons:
	std::vector< vector3<int> > cellMap; //electron Wannier cell map
	matrix cellWeights; //corresponding weights (nBands*nBands x nCells), available if needCellWeights = true
	std::shared_ptr<DistributedMatrix> Hw, Pw, Sw; //Wannier hamiltonian, dipole matrix elements and spin matrix elements 
	std::shared_ptr<DistributedMatrix> ImSigma_eeW, ImSigma_ePhW, ImSigmaP_ePhW; //linewidths in wannier basis
	void setState(StateE& state); //!< set requested properties for ik in state
	void bcastState(StateE& state, MPIUtil* mpiUtil, int root); //!< broadcast specified state on specified MPI instance
	
	//Phonons:
	std::vector< vector3<int> > phononCellMap, phononCellMapCorr; //cell map for phonon force matrix (and a possibly different corrected version for omegaSq alone)
	diagMatrix invsqrtM; //!< 1/sqrt(M) per nuclear displacement mode
	bool polar; //!< whether the system is polar (i.e. needs LO-TO correction)
	std::vector<vector3<>> Zeff; //Born effective charge for polar materials
	matrix3<> epsInf; // epsilon at infinity for polar material
	matrix phononCellWeights; //corresponding weights (nAtoms*nAtoms x nCells), available if polar
	std::shared_ptr<DistributedMatrix> OsqW; //phonon omega-squared matrix
	void setState(StatePh& state); //!< set requested properties for iq in state
	void bcastState(StatePh& state, MPIUtil* mpiUtil, int root); //!< broadcast specified state on specified MPI instance
	
	//Electron-phonon interaction:
	std::shared_ptr<DistributedMatrix> HePhW; //electron-phonon matrix elements in Wannier basis
};

//Utility functions for printing with error estimates:
void reportResult(const std::vector<matrix3<>>& result, string resultName, double unit, string unitName); //!< report a tensor result with error bars
void reportResult(const std::vector<double>& result, string resultName, double unit, string unitName); //!< report a scalar result with error bars

//Fermi and Bose functions with overflow/underflow handling:
inline double fermi(double EminusMuByT) //!< Fermi function with overflow/underflow handling
{	if(EminusMuByT < -36.) return 1.;
	else if(EminusMuByT > 36.) return 0.;
	else return 1./(1. + exp(EminusMuByT));
}
inline void fermi(double EminusMuByT, double& f, double& fbar) //!< version that computes both f and fbar=1-f without loss of precision
{	if(EminusMuByT < 0.)
	{	double boltz = exp(EminusMuByT);
		fbar = boltz / (1. + boltz);
		f = 1.-fbar;
	}
	else
	{	double boltz = exp(-EminusMuByT);
		f = boltz / (1. + boltz);
		fbar = 1.-f;
	}
}
inline double fermiPrime(double EminusMuByT) //!< Fermi function derivative w.r.t E/T (multiply by 1/T for df/dE)
{	if(fabs(EminusMuByT) > 36.) return 0.;
	else return 0.25*(std::pow(tanh(0.5*EminusMuByT), 2) - 1.);
}
inline double bose(double omegaByT) //!< Bose function with overflow/underflow handling
{	if(omegaByT > 36.) return 0.;
	else return 1./(exp(omegaByT) - 1.);
}

#endif //FEYNWANN_FEYNWANN_H
